# Generated by Django 4.1.6 on 2023-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('pType', models.CharField(max_length=50)),
                ('bType', models.CharField(max_length=50)),
            ],
        ),
    ]
